### ISSUE TITLE
yahs 版本问题

### ISSUE THREAD

**Issue by XuDong919** [gotouerina/Pore-C-analysis#1]
你好我咨询一下您用的yahs是什么版本的，我用了https://github.com/c-zhou/yahs releases下的yahs1.1,运行时显示的版本是yahs1.1a-r3，结果报错了，现在yahs 1.1 有1.1a,1.1a.1,1.1a.2

**Comment by XuDong919** [comment]
我使用yahs1.1产生的 yahs.out.bin文件是空的

**Comment by gotouerina** [comment]
是1.1a-r3，你用的bam是pairend的吗？ 单端的识别不了

**Comment by gotouerina** [comment]
还有问题可以发联系方式到我的邮箱kogoorimasaki@outlook.com，git可能回复不及时

**Comment by XuDong919** [comment]
好 谢谢啦  我用的.bam 就是wf-porec产生的null.ns.bam pairend 参数产生的  还没发现问题在哪
